
export const arabic = {
	organisation_name: "مدرستي",
	select_langugage: "حدد اللغة",
	select_langugage_arabic: "حدد اللغة",
	arabic: "عربى",
	english: "English",
	driver_name_placeholder: "اسم السائق",
	mobile_no_placeholder: "رقم الهاتف المحمول",
	locate_school: "تحديد موقع المدرسة",
	save_text: "حفظ",
	student_delivery: "تسليم الطلاب",
	student_receipt: "استلام الطالب",
	student_name: "أسم الطالب",
	class_division: "الطبقة والشعبة",
	start: "بداية",
	stop: "توقف",
	start_movement: "ابدأ الحركة",
	start_return_movement: "بدء حركة العودة",
	emergency: "حالة طوارئ",
	adjust_driver_account: "ضبط محتوى السائق",
	loading_students: "تحميل الطلاب !!!",
	off_duty_alert: "لقد قمت بتعيين بنجاح إلى خارج الخدمة",
	student_delivery_push_msg: "لقد قمت بتعيين بنجاح إلى خارج الخدمة",
	student_reciept_push_msg: "تم تلقي الطالب الخاص بك",
	start_movement_push_msg: "سائق الحافلة بدأت الحركة",
	start_return_movement_push_msg: "سائق الحافلة بدأت الحركة",
	no_students: "لم يتم تعيين الطلاب. يرجى الاتصال المشرف",
	location_text: "موقعك",
	home: "الرئيسية",
	location: "موقعك",
	account: "الحساب",
	send_notification: "إرسال الإخطار",
	alerts: "التنبيهات",
	settings: "الإعدادات",
	logout: "تسجيل خروج",
	phoneauth: "مصادقة الهاتف",
	account_setting: "إعدادات الحساب",
	edit_account: "تحرير الحساب",
	details_update_msg: "تم تحديث التفاصيل الخاصة بك بنجاح",
	no_alerts: "لا تنبيهات. سحب لتحديث",
	success: "نجاح",
	new_account_signup: "ليس لديك حساب؟ سجل هنا ",
	account_exits_login_here: " الحساب مسجل مسبقا - تسجيل الدخول هنا ",
	not_registered_please_login: "أنت غير مسجل.- الرجاء التسجيل",
	location_off_no_students: "لا طلاب !! قم بتشغيل الموقع لتحميل الطلاب",
	absent: "غائب",
	delivered: "تم التوصيل",
	received: "تم الاستلام",
	otp_sent_to: "تم إرسال كلمة مرور لمرة واحدة إلى",
	enter_to: "أدخل كلمة المرور لمرة واحدة",
	trip_created: "تم إنشاء الرحلة بنجاح",
	trip_not_created: "فشل في إنشاء الرحلة ، انقر فوق المعلومات لمزيد من التفاصيل",
	trip_details: "تفاصيل الرحلة"


}

export const english = {
	organisation_name: "Madrasati",
	select_langugage: "Select Langugage",
	select_langugage_arabic: "حدد اللغة",
	arabic: "عربى",
	english: "English",
	driver_name_placeholder: "Driver's Name",
	mobile_no_placeholder: "Mobile Number",
	locate_school: "Locate the school",
	save_text: "Save",
	student_delivery: "Student Delivery",
	student_receipt: "Student Receipt",
	student_name: "Student Name",
	class_division: "Class & Division",
	start: "Start",
	stop: "Stop",
	start_movement: "Start The Movement",
	start_return_movement: "Start The Return Movement",
	emergency: "Emergency",
	adjust_driver_account: "Adjust The Driver's Content",
	loading_students: "Loading Students !!!",
	off_duty_alert: "You have successfully set to off duty",
	student_delivery_push_msg: "Your Student Has Been Delivered",
	student_reciept_push_msg: "Your Student Has Been Received",
	start_movement_push_msg: "Bus Driver Started The Movement",
	start_return_movement_push_msg: "Bus Driver Started Return Movement",
	no_students: "No students assigned. Please contact admin",
	location_text: "Location ",
	home: "Home",
	location: "Location",
	account: "Account",
	send_notification: "Send Notification",
	alerts: "Alerts",
	settings: "Settings",
	logout: "Logout",
	phoneauth: "Phone Auth",
	account_setting: "Account Setting",
	edit_account: "Edit Account",
	details_update_msg: "Your Details Successfully Updated ",
	no_alerts: "No Alerts. Pull to refresh ",
	success: "Success",
	new_account_signup: "Don't have account? Signup Here",
	account_exits_login_here: "Already account exits? Login Here",
	not_registered_please_login: "You not registered. Please signup",
	location_off_no_students: "No students !!. Turn on location to load students",
	absent: "Absent",
	delivered: "Delivered",
	received: "Received",
	otp_sent_to: "	Otp has been sent to",
	enter_to: "Enter Otp",
	trip_created: "Trip Has Been Created Successfully",
	trip_not_created: "Faild to create trip, click on info for more details",


	trip_details: "Trip Details"


}